### ISSUE TITLE
Allow transactions to be updated via API

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenESignForms/openesignforms#146]
```
There are needs for updating an existing transaction via the APIs.

Allow a transaction template to set an UPDATE API permission (or similar) so 
only those transactions that are allowed to be updated by the API can be 
updated.

Provide an UPDATE API based on standard HTTPS POST name-value pairs, with a 
selector to ensure which transaction(s) are updated. 

Include an ability to limit the update to a particular document or to all 
documents that have a given field present.

This will also allow one transaction to update a field in another transaction.
```

Original issue reported on code.google.com by `yoz...@gmail.com` on 15 Feb 2015 at 1:45

**Comment by OpenESignForms** [comment]
May also want to consider a way to SET FIELD VALUE from another transaction.  This would allow one transaction to link to another.  It will require a way to identify the type of transaction to search for, along with a key specification (including the obvious transaction id), to identify the transaction to retrieve to apply the field spec to.

Key concern: what do do if more than one transaction is found that matches the search/filter spec? May just use the most recent until a more flexible solution is found should this be an actual consideration in practice.

**Comment by OpenESignForms** [comment]
Feature is implement only when applied to a single specified transaction -- no bulk updating or "search for" feature at this time as that has more security implications.  It includes an Update API event that is fired after the updates are done.
