### ISSUE TITLE
Embedded Images - Show an file upload field as an image in the document rather than just a file link

### ISSUE THREAD

**Issue by decryptedchaos** [OpenESignForms/openesignforms#160]
================Copied from Google Groups===============

Just wondering,  if it is currently possible to embed files (images) directly in the transaction record?  

Example:  You send a contract for services which is signed and returned,  but also has a file upload field for uploading Photocopied IDs.

Currently,  as far as i can tell,   the record only contains a aherf  embedded link to the file,  but it would be much more useful if the image could be displayed on the record (like the actual image)

i looked at the code on the record (HTML Version)   it should be a simple case of changing the aherf tag to an img tag, this could also be selected via a drop-down box from the field properties in the document builder

**Comment by OpenESignForms** [comment]
There are likely potential issues that can make this harder in a foolproof way, but we may be able to do this as long as we assume the file uploaded is an image that will render reasonably well based on where the file upload field is located in your document.

Considerations that may not be fully worked out initially:
* File uploaded is a valid image formatted file of type GIF, JPEG or PNG.
* Image height is too big.
* Image width is too wide.
* Images can be blocked by browsers so may not actually be displayed
* Should data url style embedded images be support
* Should the display of the image -- whether seen in the browser or not -- be considered as "read" by the party who views the document?  Currently, the user must click a link to indicate it's been read.

**Comment by decryptedchaos** [comment]
Yeah, i can see a few issues

    *File uploaded is a valid image formatted file of type GIF, JPEG or PNG.
     i was thinking locking the upload field to only accept  jpg,png and maybe a couple others,  i know    this isn't foolproof and could be worked around,  but for 90% of cases it should work. 



    *Image height is too big.
    *Image width is too wide.
      As for sizing,  i was thinking of hard coding the size of the display block in html, and maybe some css magic could be used to scale it up or down, to something no larger than 400x400  and maybe even that is too big (i am not sure how practical this is though) 


    *Images can be blocked by browsers so may not actually be displayed
Yeah, not much of a workaround for this,   i suppose some code which placed a text message in place saying to disable your blocker to view this image could work,  but may also be more work than its worth.
  
    *Should data url style embedded images be support
If this refers to images stored in the database,  i would say its optional,  depending on how the uploaded images are stored.  
    
    *Should the display of the image -- whether seen in the browser or not -- be considered as "read" by the party who views the document? Currently, the user must click a link to indicate it's been read.

I stopped to think about this one for a minute,  i would say that it should be considered read if the document is viewed, but only if using the "display image" mode,  otherwise business as usual,   However,  this would likely require some kind of code to hook into the transaction. some sort of if else statement which would determine if i am using display mode  then mark item viewed.  the one issue which arises from this is from one of the above stated issues,  (if the browser blocks or doesn't display the image)  in which case it really shouldn't be marked read,  however we would have to detected if the image was loaded or displayed and that could be a problem.

**Comment by OpenESignForms** [comment]
For simplicity, we've elected to add an option to the File Upload field template definition to allow for listing files (the current scheme), or to also show the image inline for uploaded images when the "display format" is set to show images inline with a max-width of 200px, 400px, 600px or 800px.  

For uploaded files that aren't specified with an image mime-type (content-type), they will still be listed.  If an image, the image is displayed above the file list information, with the max-width set to try to keep the UI from going too wide.

This should certainly work for those trying to make it work, but it's not foolproof (browsers that don't support CSS of max-width, forged file uploads that specify an image when the file is not an image should attempt to render with an IMG tag but will of course not render as the browser will not know what to do with it, image file uploaded that is not properly indicated to be an image based on its mime-type/content-type).

**Comment by decryptedchaos** [comment]
Indeed,  This should work 90% of the time,  and maybe it can even be improved at some point.  

I think it will add a very useful feature to the system.

**Comment by OpenESignForms** [comment]
This will be added in the upcoming release this month.  We did add an option for "image only" uploads, blocking files uploaded that don't have the expected mime/content-types.
