### ISSUE TITLE
What is the best way to pull in our own data into the iframe?

### ISSUE THREAD

**Issue by peiledoir** [OpenESignForms/openesignforms#161]
We have the iframe working in a modal window and we have 'Fields' within the document. We would like to populate some of these fields with dynamic content from the parent window, but due to cross origin policies, we cannot transfer data to the iframe. What is your best way to pull data into the iframe?

**Comment by peiledoir** [comment]
I look to have found it for anyone else viewing in the future:
If you create a parameter in the url for the iframe and then name the field the exact same as that parameter, then it works great.

**Comment by OpenESignForms** [comment]
Glad you resolved it yourself.  For questions, we ask that you don't create an issue, but use the public forums that are more likely to be read to answer questions: 

https://groups.google.com/forum/#!forum/openesignformsdev

But the general idea is that initial parameters can be passed in on the URL or via POST, etc. to pre-fill.  If the param names match data field names, they will auto-prefill.  If not, you can set a field's value to be whatever the parameter name is from the transaction data (all initial data used to start a transaction is stored in the transaction data object).

The details for such integration needs can be seen here:

https://github.com/OpenESignForms/openesignforms/wiki/ProgrammingGuide_Integration_API
