### ISSUE TITLE
ï¿½ character in DbSetup suspected of causing encoding issues

### ISSUE THREAD

**Issue by IQuant** [OpenESignForms/openesignforms#163]
DbSetup.java v16.1.16

Found 19 occurrences of Unicode Replacement Character (U+FFFD)  suspected of causing issues during installation.  
ie.  Ansi Enoding renders 'ï¿½' symbol

Lines 629 - 630
		String[] moneyOptions = { "123456789.12","ï¿½123,456,789","ï¿½123,456,789.12","ï¿½123,456,789","ï¿½123,456,789.12"};
		String[] moneyValues  = { "##############0.00","'ï¿½'###,###,###,###,##0","'ï¿½'###,###,###,###,##0.00","'ï¿½'###,###,###,###,##0","'ï¿½'###,###,###,###,##0.00"};

Line 3792
ddvo.setOption("ï¿½LAND ISLANDS");

Lines 5958 - 5059
"'ï¿½' - Fixed pound sign\n" +
"'ï¿½' - Fixed euro sign\n" +

Lines 5097 - 5110

       	ddvo.setOption("ï¿½123,456,789");
        	ddvo.setValue("'ï¿½'###,###,###,###,##0");
        	optionList.add(ddvo);
        	ddvo = DropDownVersionOption.Manager.createNew(ddv, order++);
        	ddvo.setOption("ï¿½123,456,789.12");
        	ddvo.setValue("'ï¿½'###,###,###,###,##0.00");
        	optionList.add(ddvo);
        	ddvo = DropDownVersionOption.Manager.createNew(ddv, order++);
        	ddvo.setOption("ï¿½123,456,789");
        	ddvo.setValue("'ï¿½'###,###,###,###,##0");
        	optionList.add(ddvo);
        	ddvo = DropDownVersionOption.Manager.createNew(ddv, order++);
        	ddvo.setOption("ï¿½123,456,789.12");
        	ddvo.setValue("'ï¿½'###,###,###,###,##0.00");

http://goo.gl/7hnVfg

57 Compiling Errors:
                           
DbSetup.java:5110: error: unmappable character for encoding ASCII

**Comment by OpenESignForms** [comment]
Don't understand. We have no compile errors in our code, and Java (Unicode) and our system in general use UTF8 for all character encoding and no other encoding is supported.  The "broken" symbol you see I suspect is the EURO symbol.

**Comment by OpenESignForms** [comment]
Interesting...unsure when this went bad.  The euro and pound currency symbols do seem corrupted in the code, resulting in those values being wrong in the drop down as well.

**Comment by OpenESignForms** [comment]
This has been corrected in the DbSetup.java and will be included in the 16.2.13 release.  For those who installed when it was not working and need the correct values, please update the following drop downs in your ESF/Library/Template:

ESF_Countries - update second entry option -> value to be: 
Åland Islands   ->   AX

ESF_MoneyFormat - update entries 8-11 option -> value to be:
£123,456,789   ->  '£'###,###,###,###,##0
£123,456,789.12   ->   '£'###,###,###,###,##0.00
€123,456,789    ->   '€'###,###,###,###,##0
€123,456,789.12   ->    '€'###,###,###,###,##0.00
