### ISSUE TITLE
HTML Editor

### ISSUE THREAD

**Issue by zosocanuck** [OpenESignForms/openesignforms#165]
Hi,

I have a brand new installation of 16.1.16, however when I attempt to edit a document the HTML editor does not show.  Is there anything I need to do post-installation to enable this plugin?

**Comment by OpenESignForms** [comment]
Nothing extra if just using the released materials and you are not building the code yourself.  If building yourself, you do need to run Vaadin widgetset compilations (creates the javascript hooks) and of course you must have the WEB-INF/lib/vaadinckeditor7.10.6.jar deployed.

**Comment by zosocanuck** [comment]
Hi,

Thanks for the follow up.  Turns out that I had to remove ckeditor from the .gitignore file locat at:
webapps/ROOT/VAADIN/widgetsets/com.esignforms.open.vaadin.widgetset.Open_esignformsvaadinWidgetset.

I then added the files via git and did a push and everything is working.
