### ISSUE TITLE
Using date "now"

### ISSUE THREAD

**Issue by zosocanuck** [OpenESignForms/openesignforms#168]
Hi,

I have a field set to display the current date using "now" and the first form has the correct day, however I have a follow on form that sets another field based on this day and the days are off by one.  So the first form with February 26, 2016 shows as February 25, 2016 on the 2nd form.  Also when i re-open the link to fill in the form the day is then 2 days behind, etc.  Any ideas?

**Comment by OpenESignForms** [comment]
If a date is losing a day each time you access it, it sounds like you have a custom logic rule setting the date to be one day earlier.  Without being able to see your setup, we cannot help further.  Can you provide remote access for us to see the issue, or screen shots of the field setups, any custom logic rules that set them, etc.

**Comment by zosocanuck** [comment]
Can you provide a private email address where I can send you some more details?

**Comment by OpenESignForms** [comment]
yozons@gmail.com

**Comment by OpenESignForms** [comment]
We created Doc1 and Doc2, each with a current date set via +0 or now in the initial value, and Doc2.doc2Date = Doc1.date and the dates copied over just fine.  If you can share what is needed to reproduce the issue, we can investigate further, but we see no issue in our testing based on your scenario.

**Comment by OpenESignForms** [comment]
Are you on the latest release of OpenESF?  We generally don't attempt to resolve bug reports on any prior version as it's possible that a fix has already been done that affects whatever you are seeing.

**Comment by zosocanuck** [comment]
I am using v16.1.16.

**Comment by OpenESignForms** [comment]
Yes, the demo system login info is at the bottom of the AGPL project page: https://open.esignforms.com

You can run the "David Date Test" transaction.  It uses the package David/DateDocs, which uses the documents DateDoc1 and DateDoc2 in library Partners/David.  DateDoc1 just sets a date field to 'now' in the initial values. DateDoc2 has a similar current date, as well as a date that is set from DateDoc1 (done in the package's custom logic).

The fact that your date is wrong when you first get it suggests that's the real issue, not the assignment of the date.  I'm not sure why your Java system thinks the date is one day earlier unless your system clock is wrong.  Is the correct date/time shown in the bottom when you login to your OpenESF?

**Comment by zosocanuck** [comment]
Date is correct as shown on the bottom.  Deployment is on an instance of OpenShift with Java:

java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (rhel-2.6.4.0.el6_7-i386 u95-b00)
OpenJDK Server VM (build 24.95-b01, mixed mode)

Server date is EST and is accurate.

**Comment by OpenESignForms** [comment]
No idea what you are seeing. Very odd setup that we have no answer for.  If you find the underlying cause and it's a software error of ours, let us know.

Here's a test that shows it working normally:

https://open.esignforms.com/demo/S/David/DateDocs

Are you sure you have no custom logic that's adjusting the date on page review?  It looks correct when you start, and decrements the date on review.

**Comment by zosocanuck** [comment]
Yes, it's weird, and has been happening since I did a fresh deployment of
v16.1.16.  Signature date is fine but if I use any date field the same
behavior is exhibited.  Note that this deployment is on Tomcat 7 with JDK 7
on RedHat OpenShift.  No custom logic initially then I started playing
around with adding a day to compensate, but that is it.

Is there any detailed Java debugging that I can turn on to diagnose?

Anyone else deployed in OpenShift or has experienced this?

**Comment by OpenESignForms** [comment]
Seems hard to believe there's any issue in Java, Tomcat or Linux, and OpenESF doesn't do this in any deployment we've seen.  The only way we can make a date behave like yours is if you have custom logic (in the document or package) that decrements the date on page review.  But that would appear in the activity log.  

You can debug using standard Java debugging (we do it via Eclipse on our dev machines), and the esf.log file for your deployment defaults to show debug messages (log4j ALL) so you can look there as you are testing.

**Comment by OpenESignForms** [comment]
Our best guess is that you might try running the Oracle JVM 1.8 instead of OpenJDK 7.  The behavior of creating a date object from a string that results in the prior date is odd.  Of course, if you discover a coding issue in OpenESF, we'll be happy to address it.

**Comment by zosocanuck** [comment]
I just tried with Oracle Java

java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

With Tomcat 9 running on an OpenShift DIY cartridge.

The date still ends being pushed back one day after hitting continue to
review and then going back to make changes.

**Comment by OpenESignForms** [comment]
That's very odd.  I think the only hope is to run it using remote Java debugging via Eclipse and see where the "day before" comes from.  It seems that creating an EsfDate using a string date gets it off by one day, which of course makes no sense that it is happening on your deployment.  Most likely that's in EsfDate.CreateGuessFormat().  Or perhaps where the data is saved when going from edit to review mode in DocumentPageBean.validatePartyInput() around line 2124 (inside the if fieldTemplate.isTypeDate()).

Remote Java debugging generally requires your Tomcat's Java have the runtime option: 
-agentlib:jdwp=transport=dt_socket,server=y,address=49090,server=y,suspend=n  

And you'll need to make sure whatever 'address' port (49090 here) number you use is open in your firewall.

**Comment by zosocanuck** [comment]
I have used Eclipse in the past but not as familiar with remote debugging,
and have followed this:

https://developer.jboss.org/en/tools/blog/2012/06/27/deploy-from-eclipse-to-openshift-in-a-breeze

I'm able to get to the remote OpenJDK Server VM from eclipse.

I've set a breakpoint but how to step through?  Any tips or online
documentation you can forward?

**Comment by OpenESignForms** [comment]
We don't have any eclipse info, but it's generally easy when in the DEBUG perspective that should open.  There are buttons to step over a line (execute the line), or step into a method (as well as menu items that do the same).  These are the only two you need besides setting a breakpoint.  "Step return" is also useful if you just want to return to the method's calling spot.

**Comment by zosocanuck** [comment]
Observation: Changing to UTC from System Config -> Deployment -> Default
time zone doesn't exhibit the one day behind behavior.

**Comment by zosocanuck** [comment]
Workaround:

Add/modify the following to .openshift/action_hooks/pre_start_jbossews

export _JAVA_OPTIONS="-Duser.timezone=America/Los_Angeles
-Desf.deploybase=${ESF_DEPLOYMENT_BASE}"

Of course select the appropriate timezone.

**Comment by OpenESignForms** [comment]
Good job figuring it out, though it's still unclear why there's an issue unless somehow Java itself misinterprets the server's current time as being in another timezone.  As we move along, we hope to perhaps switch our EsfDate class to use Java 8 local dates that are not related to time whatsoever (like java.util.Date).

If you have more information or the like and think a fix is required, we can re-open this issue, but for now, we'll consider this closed.
