### ISSUE TITLE
How can I Upload and send pdf without creating the pdf content through document creation ?

### ISSUE THREAD

**Issue by Prasanthmv** [OpenESignForms/openesignforms#176]
HI,
I have gone through the demo site . I want to upload my pdf file and make signature on that document,not on the document created through library . How can I do that ?Is there any way for that ?Please help .

**Comment by OpenESignForms** [comment]
No. OpenESF is a web-based solution that works with all devices without requiring specialized software, whereas filling/signing inside a PDF does.

The closest you can do is a proxy/by-reference signature, one that shows the PDF, and then perhaps has language like "Do not sign until you have clicked on the above link and read the document.  By signing below, I assert I have read and agree to the terms contained in the above document (in PDF format)."  OpenESF can ensure that the PDF uploaded is not changed and thus the by reference signature would suffice (many contracts include terms by reference).
