### ISSUE TITLE
Signature from Documen

### ISSUE THREAD

**Issue by 9foxlabs** [OpenESignForms/openesignforms#181]
Is it possible to have a current online "In House" document/waiver that can be signed by patient without having the patient receive the email to sign? 
I would like patient to sign waiver and have the signed waiver sent to myself and the patient. Does the patient Have to sign via email? We need them to sign document in the office and email that signed document to them.

Is there an api for this to product with PHP?

Thank you

**Comment by OpenESignForms** [comment]
We'd prefer questions be posted in the forum: https://groups.google.com/forum/#!forum/openesignformsdev

Few look through past issues for any discussions.
