### ISSUE TITLE
create_db not working...

### ISSUE THREAD

**Issue by asiav** [OpenESignForms/openesignforms#183]
Hi,
I try few times to run this setup but get issues when ./create_db 

./create_db - Sat Sep 1 08:22:18 CDT 2018 - Creating DB role 'esignforms' and database 'esignforms' at location '/home/esignforms/deployments/esignforms/current/db'.
Is this okay? (y/n)y
./create_db - Sat Sep 1 08:22:24 CDT 2018 - Creating OpenESF DB Role 'esignforms' and database 'esignforms'...
DROP DATABASE IF EXISTS esignforms ;
NOTICE:  database "esignforms" does not exist, skipping
DROP DATABASE
DROP ROLE IF EXISTS esignforms ;
ERROR:  current user cannot be dropped
DROP TABLESPACE IF EXISTS esignforms_space ;
NOTICE:  tablespace "esignforms_space" does not exist, skipping
DROP TABLESPACE
CREATE ROLE esignforms WITH LOGIN PASSWORD 'esignforms' NOCREATEDB NOCREATEROLE ;
ERROR:  role "esignforms" already exists
CREATE TABLESPACE esignforms_space LOCATION '/home/esignforms/deployments/esignforms/current/db' ;

few issues i found in the guide on the way...

1. typo in : 
Copy scripts into esignforms home directory under bin and make deployment directory
sudo su
sudo - esignforms -> should be "su - esignforms"

2. Grant postgres access to deployment directory
chown -R postgres.postgres /opt/esignforms/deployments/
the folder doesn't exist @ this step, it been created few steps after - am gassing this one give the issues creating DB.

 3. Install the Open eSignForms Database
source /opt/esignforms/profile
cd /opt/esignforms/database/postgresql/ddl/

should be home not opt: 
source /home/esignforms/profile
cd /home/esignforms/database/postgresql/ddl/

please help..

**Comment by OpenESignForms** [comment]
What guide has the typos?
Note that none of the information you have here is in the Yozons guides (from the look of the commands), so while we can correct some, as we didn't write them nor do we test them, it's hard for us to know for sure that they are correct or wrong.  
Note that Yozons recommends installing PG as a user account like 'esignforms' (the DBA user), and would not then use 'esignforms' as a deployment name.  'esignforms' should remain the DBA super-admin, and you create an OpenESF deployment using a meaningful name (as we run many deployments on a single server, but you are free to have just one) like 'test' or 'demo' or 'prod' or 'companyname' etc.  That way, you can drop users and databases for these deployments while acting as the 'esignforms' DBA.

**Comment by asiav** [comment]
Oops 

Guide: how to install eSignForms on EC2

**Comment by OpenESignForms** [comment]
This shows more that we should perhaps simply stop linking to this wiki that was written by parties outside of Yozons.  It appears to be very out of date, and we'll remove the link from our main area and leave the wiki in place.  We don't want to be in the position of having to maintain wikis other people write.
We have done the first and third items as we're not really sure what needs to be fixed for your second issue.

**Comment by asiav** [comment]
Thanks for replay. 
If I like to setup on AWS, can you point me to the latest/current guide?

**Comment by OpenESignForms** [comment]
Nothing special as our guides were mostly for developers, but we do include a bunch of details (you should read it all before using it as it isn't a step by step guide per se.  Look for the Linux steps at the bottom for the closest we have:
https://github.com/OpenESignForms/openesignforms/wiki/InstallationUsingVaadin7

**Comment by OpenESignForms** [comment]
We're going to close this request.  Note that we do offer AGPL shared hosting and Amazon EC2 Linux/RedHat/CentOS installation for those who just want the AGPL version and don't care about commercial licenses or support.
